services:
  db:
    image: mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - data-db:/var/lib/mysql
    restart: unless-stopped
  
  php:
    build:
      context: .
      dockerfile: php.Dockerfile
    volumes:
      - ./app:/var/www/html
    depends_on:
      - db
    restart: unless-stopped

  nginx:
    image: nginx:alpine
    ports:
      - 80
      - 443
    volumes:
      - ./app:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - php
    restart: unless-stopped
  
  sftp:
    image: atmoz/sftp
    volumes:
      - ./app:/home/sftpuser/ftp/upload
      - data-sftp:/home/sftpuser/.ssh
    ports:
      - "2222:22"
    environment:
      - SFTP_USERS=${SFTP_USER}:${SFTP_PASSWORD}:83:100:/home/sftpuser/ftp/upload
    command: sh -c "chown -R 83:100 /home/sftpuser/ftp/upload && chmod -R 777 /home/sftpuser/ftp/upload && /usr/sbin/sshd -D -e"
    restart: unless-stopped
    
volumes:
  data-db:
  data-sftp:
