services:
  db:
    image: mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - dokploy-network
    restart: unless-stopped

  sftp:
    image: corilus/sftp:alpine
    volumes:
      - ./app:/var/www/html
    ports:
     - 2222:22
    environment:
     - SFTP_USERS=${SFTP_USER}:${SFTP_PASSWORD}:82:100:/var/www/html/sftp
    depends_on:
      - nginx
    networks:
      - dokploy-network
    restart: unless-stopped
    
  php:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./app:/var/www/html
    depends_on:
      - db
    networks:
      - dokploy-network
    restart: unless-stopped

  nginx:
    image: nginx:alpine
    ports:
      - 80
      - 443
    volumes:
      - ./app:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - php
    networks:
      - dokploy-network
    restart: unless-stopped

networks:
  dokploy-network:
    external: true
    driver: overlay

volumes:
  db-data:
