services:
  php:
    build:
      context: .
      dockerfile: php.Dockerfile
    volumes:
      - ./app:/var/www/html
    restart: unless-stopped

  nginx:
    image: nginx:alpine
    ports:
      - 80
      - 443
    volumes:
      - ./app:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - php
    restart: unless-stopped

  sftp:
    image: atmoz/sftp:alpine
    ports:
      - "${SFTP_PORT}"
    volumes:
      - ./app:/home/${SFTP_USER}/upload
    command: sh -c "cd / && apk update && apk add -q --no-cache nano && chown -R 33:33 /home/${SFTP_USER}/upload && /entrypoint \'${SFTP_USER}:${SFTP_PASSWORD}:33:33:/upload\'"
    restart: unless-stopped

volumes:
  data-db:
