services:
  db:
    image: mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - dokploy-networkss
    restart: unless-stopped
  
  php:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./app:/var/www/html
    depends_on:
      - db
    networks:
      - dokploy-networkss
    restart: unless-stopped

  nginx:
    image: nginx:alpine
    ports:
      - 80
      - 443
    volumes:
      - ./app:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - php
    networks:
      - dokploy-networkss
    restart: unless-stopped

networks:
  dokploy-networkss:
    external: true
    driver: bridge

volumes:
  db-data:
  data:
