services:
  db:
    image: mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - data-db:/var/lib/mysql
    restart: unless-stopped

  php:
    build:
      context: .
      dockerfile: php.Dockerfile
    volumes:
      - ./app:/var/www/html
    depends_on:
      - db
    restart: unless-stopped

  nginx:
    image: nginx:alpine
    ports:
      - 80
      - 443
    volumes:
      - ./app:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - php
    restart: unless-stopped

  sftp:
    build:
      context: .
      dockerfile: sftp.Dockerfile
    args:
        SFTP_USER: "${SFTP_USER}"
        SFTP_UID: 1000
        SFTP_GID: 1000
    ports:
      - "22:22"
    volumes:
      - ./app:/home/${SFTP_USER}/upload
    command: "${SFTP_USER}:${SFTP_PASSWORD}:1000:100:/upload"
    restart: unless-stopped

volumes:
  data-db:
