services:
  db:
    image: mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - data-db:/var/lib/mysql
    restart: unless-stopped
  
  php:
    build:
      context: .
      dockerfile: php.Dockerfile
    volumes:
      - ./app:/var/www/html
    depends_on:
      - db
    restart: unless-stopped

  nginx:
    image: nginx:alpine
    ports:
      - 80
      - 443
    volumes:
      - ./app:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - php
    restart: unless-stopped
  
  sftp:
    image: fauria/vsftpd
    volumes:
      - ./app:/home/vsftpd
      - data-sftp:/data-sftp
    ports:
      - 0.0.0.0:20:20
      - 0.0.0.0:21:21
    environment:
      - FTP_USER=${FTP_USER}
      - FTP_PASS=${FTP_PASSWORD}
      #- SFTP_USERS=${SFTP_USER}:${SFTP_PASSWORD}:0:0::upload
    #command: sh -c "chown -R 83:100 /var/www/html && chmod -R 755 /var/www/html && /usr/sbin/sshd -D -e"
    restart: unless-stopped
    
volumes:
  data-db:
  data-sftp:
