version: '3.8'

services:
  nginx:
    image: nginx:alpine
    ports:
      - 80
      - 443
      - 9000
    volumes:
      - ./app:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    working_dir: /var/www/html
    depends_on:
      - php
    networks:
      - lemp-net

  php:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./app:/var/www/html
    working_dir: /var/www/html
    depends_on:
      - db
    networks:
      - lemp-net

  db:
    image: mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - lemp-net

networks:
  lemp-net:

volumes:
  db-data:
