services:
  db:
    image: mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - data-db:/var/lib/mysql
    restart: unless-stopped

  php:
    build:
      context: .
      dockerfile: php.Dockerfile
    volumes:
      - ./app:/var/www/html
    depends_on:
      - db
    restart: unless-stopped

  nginx:
    image: nginx:alpine
    ports:
      - 80
      - 443
    volumes:
      - ./app:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - php
    restart: unless-stopped

  ftp:
    image: fauria/vsftpd
    ports:
      - 21:21
      - 20:20
      - 21100-21110:21100-21110
    volumes:
      - ./app:/home/vsftpd/ftpuser/${FTP_USER}
    environment:
      FTP_USER: "${FTP_USER}"
      FTP_PASS: "${FTP_PASSWORD}"
      PASV_ENABLE: "YES"
      UMASK: "022"
      LOCAL_UMASK: "022"
      FILE_OPEN_MODE: "0644"
      FTP_UID: "14"
      FTP_GID: "50"
      VIRTUAL_ROOT: "/home/vsftpd/ftpuser/${FTP_USER}"
    restart: unless-stopped

volumes:
  data-db:
