version: '3.6'

services:
  db:
    image: mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - data-db:/var/lib/mysql
    restart: unless-stopped
  
  php:
    build:
      context: .
      dockerfile: php.Dockerfile
    volumes:
      - ./app:/var/www/html
    depends_on:
      - db
    restart: unless-stopped

  nginx:
    image: nginx:alpine
    # 80 ve 443 portlarını host makineye map'liyoruz
    ports:
      - 80
      - 443
    volumes:
      - ./app:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - php
    restart: unless-stopped
  
  # VSFTPD SERVİSİ: FTP ile dosya yönetimi için
  vsftpd:
    image: fauria/vsftpd
    container_name: ftp_server
    restart: always
    environment:
      # FTP Giriş Bilgileri (Bu değerleri .env dosyasında saklayın!)
      - FTP_USER=${SFTP_USER}
      - FTP_PASS=${SFTP_PASSWORD}
      # PASİF MOD AYARLARI (FTP bağlantı sorunlarını çözmek için KRİTİKTİR)
      - PASV_ENABLE=YES
      # DİKKAT: Buraya sunucunuzun GENEL IP adresini veya alan adını yazın.
      - PASV_ADDRESS=${SFTP_IP}
      - PASV_MIN_PORT=21100
      - PASV_MAX_PORT=21110
    ports:
      # FTP Kontrol Portu
      - 21:21
      # FTP Veri Portu (Aktif Mod)
      - 20:20
      # Pasif Port Aralığı (Güvenlik duvarında bu aralığı açmayı unutmayın)
      - 21100-21110:21100-21110
    volumes:
      # Web dosyalarına erişim için, host'taki `./app` klasörünü FTP ana dizinine (`/home/vsftpd`) bağlıyoruz.
      - ./app:/home/vsftpd 
      # İsteğe bağlı: Log dosyalarını host'ta tutmak için
      - ./ftp_logs:/var/log/vsftpd

volumes:
  data-db:
