services:
  db:
    image: mariadb:latest
    environment:
      MARIADB_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD}
      MARIADB_DATABASE: ${MARIADB_DATABASE}
      MARIADB_USER: ${MARIADB_USER}
      MARIADB_PASSWORD: ${MARIADB_PASSWORD}
    volumes:
      - data-db:/var/lib/mysql
    healthcheck:
     test: ["CMD", "mariadb-admin", "ping", "-h", "localhost"]
     interval: 5s
     timeout: 3s
     retries: 5
    restart: unless-stopped
    
  php:
    build:
      context: .
      dockerfile: php.Dockerfile
    volumes:
      - ./app:/var/www/html
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped

  nginx:
    image: nginx:alpine
    ports:
      - 80
      - 443
    volumes:
      - ./app:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - php
    restart: unless-stopped

  sftp:
    image: atmoz/sftp:alpine
    ports:
      - "${SFTP_PORT}"
    volumes:
      - ./app:/home/${SFTP_USER}/upload
    command: sh -c "cd / && apk update && apk add -q --no-cache nano && chown -R 1001:100 /home/${SFTP_USER}/upload && /entrypoint \'${SFTP_USER}:${SFTP_PASSWORD}:1001:100:/upload\'"
    restart: unless-stopped

volumes:
  data-db:
