services:
  db:
    image: mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - data-db:/home
      - data-db:/var/lib/mysql
    restart: unless-stopped
  
  php:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - data-php:/home
      - ./app:/var/www/html
    depends_on:
      - db
    restart: unless-stopped

  nginx:
    image: nginx:alpine
    ports:
      - 80
      - 443
    volumes:
      - data-nginx:/home
      - ./app:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - php
    restart: unless-stopped
  
  sftp:
    image: atmoz/sftp
    volumes:
      - ./app:/home/sftpuser/ftp/upload
      - data-sftp:/home
    ports:
      - "2222:22"
    command: ${SFTP_USER}:${SFTP_PASSWORD}:83:100::upload
    restart: unless-stopped
    
volumes:
  data-db:
  data-php:
  data-nginx:
  data-sftp:
