services:
  db:
    image: mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD: ${PROJECT_NAME}-${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${PROJECT_NAME}-${MYSQL_DATABASE}
      MYSQL_USER: ${PROJECT_NAME}-${MYSQL_USER}
      MYSQL_PASSWORD: ${PROJECT_NAME}-${MYSQL_PASSWORD}
    volumes:
      - ${PROJECT_NAME}-data-db:/home/${PROJECT_NAME}
      - ${PROJECT_NAME}-data-db:/var/lib/mysql
    networks:
      - ${PROJECT_NAME}-network
    restart: unless-stopped
  
  php:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ${PROJECT_NAME}-data-php:/home/${PROJECT_NAME}
      - ./app:/var/www/html
    depends_on:
      - db
    networks:
      - ${PROJECT_NAME}-network
    restart: unless-stopped

  nginx:
    image: nginx:alpine
    ports:
      - 80
      - 443
    volumes:
      - ${PROJECT_NAME}-data-nginx:/home/${PROJECT_NAME}
      - ./app:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - php
    networks:
      - ${PROJECT_NAME}-network
    restart: unless-stopped

networks:
  ${PROJECT_NAME}-network:
    driver: bridge

volumes:
  ${PROJECT_NAME}-data-db:
  ${PROJECT_NAME}-data-php:
  ${PROJECT_NAME}-data-nginx:
